/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Thumbnail: typeof import('./../components/thumbnail/Thumbnail.vue')['default']
    ThumbnailList: typeof import('./../components/thumbnail/ThumbnailList.vue')['default']
    Toolbar: typeof import('./../components/toolbar/Toolbar.vue')['default']
    ToolButton: typeof import('./../components/toolbar/ToolButton.vue')['default']
  }
}
